import type { VocabTopic } from './types';

/**
 * Raw data kept human-readable; we'll normalize each vocabulary so that
 * the exported `vocabTopicsData` guarantees: only letters (A-Za-z),
 * lowered, and at most 6 characters.
 */
export const vocabTopicsData: VocabTopic[] = [
  // Topic 1: Animals
  {
    id: '1',
    text: 'Animals',
    options: [
      { id: '1', vocabulary: 'dog' },
      { id: '2', vocabulary: 'cat' },
      { id: '3', vocabulary: 'bird' },
      { id: '4', vocabulary: 'fish' },
      { id: '5', vocabulary: 'horse' },
      { id: '6', vocabulary: 'cow' },
      { id: '7', vocabulary: 'sheep' },
      { id: '8', vocabulary: 'goat' },
      { id: '9', vocabulary: 'pig' },
      { id: '10', vocabulary: 'rabbit' },
      { id: '11', vocabulary: 'deer' },
      { id: '12', vocabulary: 'lion' },
      { id: '13', vocabulary: 'tiger' },
      { id: '14', vocabulary: 'bear' },
      { id: '15', vocabulary: 'elephant' },
      { id: '16', vocabulary: 'giraffe' },
      { id: '17', vocabulary: 'zebra' },
      { id: '18', vocabulary: 'kangaroo' },
      { id: '19', vocabulary: 'koala' },
      { id: '20', vocabulary: 'monkey' },
      { id: '21', vocabulary: 'chimp' },
      { id: '22', vocabulary: 'gorilla' },
      { id: '23', vocabulary: 'fox' },
      { id: '24', vocabulary: 'wolf' },
      { id: '25', vocabulary: 'otter' },
      { id: '26', vocabulary: 'seal' },
      { id: '27', vocabulary: 'whale' },
      { id: '28', vocabulary: 'dolphin' },
      { id: '29', vocabulary: 'shark' },
      { id: '30', vocabulary: 'octopus' },
      { id: '31', vocabulary: 'crab' },
      { id: '32', vocabulary: 'lobster' },
      { id: '34', vocabulary: 'swan' },
      { id: '35', vocabulary: 'duck' },
      { id: '36', vocabulary: 'goose' },
      { id: '38', vocabulary: 'eagle' },
      { id: '39', vocabulary: 'hawk' },
      { id: '40', vocabulary: 'owl' },
      { id: '41', vocabulary: 'bat' },
      { id: '43', vocabulary: 'mouse' },
      { id: '44', vocabulary: 'rat' },
      { id: '46', vocabulary: 'camel' },
      { id: '47', vocabulary: 'donkey' },
      { id: '49', vocabulary: 'rhino' },
      { id: '50', vocabulary: 'hippo' },
    ],
  },

  // Topic 2: Food
  {
    id: '2',
    text: 'Food',
    options: [
      { id: '51', vocabulary: 'apple' },
      { id: '52', vocabulary: 'banana' },
      { id: '53', vocabulary: 'orange' },
      { id: '54', vocabulary: 'grape' },
      { id: '57', vocabulary: 'pineapple' },
      { id: '58', vocabulary: 'mango' },
      { id: '59', vocabulary: 'avocado' },
      { id: '60', vocabulary: 'peach' },
      { id: '61', vocabulary: 'pear' },
      { id: '62', vocabulary: 'cherry' },
      { id: '63', vocabulary: 'lemon' },
      { id: '64', vocabulary: 'lime' },
      { id: '68', vocabulary: 'carrot' },
      { id: '69', vocabulary: 'potato' },
      { id: '70', vocabulary: 'tomato' },
      { id: '71', vocabulary: 'cucumber' },
      { id: '72', vocabulary: 'lettuce' },
      { id: '73', vocabulary: 'spinach' },
      { id: '74', vocabulary: 'onion' },
      { id: '75', vocabulary: 'garlic' },
      { id: '76', vocabulary: 'ginger' },
      { id: '77', vocabulary: 'mushroom' },
      { id: '78', vocabulary: 'pepper' },
      { id: '79', vocabulary: 'corn' },
      { id: '80', vocabulary: 'peas' },
      { id: '81', vocabulary: 'beans' },
      { id: '82', vocabulary: 'rice' },
      { id: '83', vocabulary: 'pasta' },
      { id: '84', vocabulary: 'bread' },
      { id: '85', vocabulary: 'cheese' },
      { id: '86', vocabulary: 'milk' },
      { id: '87', vocabulary: 'yogurt' },
      { id: '88', vocabulary: 'egg' },
      { id: '89', vocabulary: 'chicken' },
      { id: '90', vocabulary: 'beef' },
      { id: '91', vocabulary: 'pork' },
      { id: '92', vocabulary: 'salmon' },
      { id: '93', vocabulary: 'tuna' },
      { id: '94', vocabulary: 'shrimp' },
      { id: '95', vocabulary: 'choco' },
      { id: '96', vocabulary: 'cake' },
      { id: '97', vocabulary: 'cookie' },
      { id: '98', vocabulary: 'cream' },
      { id: '99', vocabulary: 'honey' },
      { id: '100', vocabulary: 'butter' },
    ],
  },

  // Topic 3: Travel
  {
    id: '3',
    text: 'Travel',
    options: [
      { id: '101', vocabulary: 'airport' },
      { id: '102', vocabulary: 'airplane' },
      { id: '103', vocabulary: 'baggage' },
      { id: '104', vocabulary: 'passport' },
      { id: '105', vocabulary: 'visa' },
      { id: '106', vocabulary: 'ticket' },
      { id: '107', vocabulary: 'boarding' },
      { id: '108', vocabulary: 'gate' },
      { id: '109', vocabulary: 'terminal' },
      { id: '110', vocabulary: 'customs' },
      { id: '111', vocabulary: 'immigration' },
      { id: '112', vocabulary: 'hotel' },
      { id: '113', vocabulary: 'booking' },
      { id: '114', vocabulary: 'check-in' },
      { id: '115', vocabulary: 'check-out' },
      { id: '116', vocabulary: 'lobby' },
      { id: '117', vocabulary: 'concierge' },
      { id: '118', vocabulary: 'elevator' },
      { id: '119', vocabulary: 'escalator' },
      { id: '120', vocabulary: 'subway' },
      { id: '121', vocabulary: 'train' },
      { id: '122', vocabulary: 'station' },
      { id: '123', vocabulary: 'platform' },
      { id: '124', vocabulary: 'map' },
      { id: '125', vocabulary: 'guide' },
      { id: '126', vocabulary: 'tour' },
      { id: '127', vocabulary: 'itinerary' },
      { id: '128', vocabulary: 'sightseeing' },
      { id: '129', vocabulary: 'museum' },
      { id: '130', vocabulary: 'landmark' },
      { id: '131', vocabulary: 'beach' },
      { id: '132', vocabulary: 'mountain' },
      { id: '133', vocabulary: 'hiking' },
      { id: '134', vocabulary: 'backpack' },
      { id: '135', vocabulary: 'suitcase' },
      { id: '136', vocabulary: 'taxi' },
      { id: '137', vocabulary: 'bus' },
      { id: '138', vocabulary: 'ferry' },
      { id: '139', vocabulary: 'cruise' },
      { id: '140', vocabulary: 'road trip' },
      { id: '141', vocabulary: 'hostel' },
      { id: '142', vocabulary: 'camping' },
      { id: '143', vocabulary: 'guidebook' },
      { id: '144', vocabulary: 'souvenir' },
      { id: '145', vocabulary: 'photo' },
      { id: '146', vocabulary: 'currency' },
      { id: '147', vocabulary: 'exchange' },
      { id: '148', vocabulary: 'insurance' },
      { id: '149', vocabulary: 'tour plan' },
      { id: '150', vocabulary: 'travel card' },
    ],
  },

  // Topic 4: Technology
  {
    id: '4',
    text: 'Technology',
    options: [
      { id: '151', vocabulary: 'computer' },
      { id: '152', vocabulary: 'internet' },
      { id: '153', vocabulary: 'software' },
      { id: '154', vocabulary: 'hardware' },
      { id: '155', vocabulary: 'keyboard' },
      { id: '156', vocabulary: 'mouse' },
      { id: '157', vocabulary: 'monitor' },
      { id: '158', vocabulary: 'laptop' },
      { id: '159', vocabulary: 'phone' },
      { id: '160', vocabulary: 'tablet' },
      { id: '161', vocabulary: 'app' },
      { id: '162', vocabulary: 'browser' },
      { id: '163', vocabulary: 'website' },
      { id: '164', vocabulary: 'server' },
      { id: '165', vocabulary: 'database' },
      { id: '166', vocabulary: 'cloud' },
      { id: '167', vocabulary: 'AI' },
      { id: '168', vocabulary: 'algorithm' },
      { id: '169', vocabulary: 'program' },
      { id: '170', vocabulary: 'code' },
      { id: '171', vocabulary: 'developer' },
      { id: '172', vocabulary: 'engineer' },
      { id: '173', vocabulary: 'network' },
      { id: '174', vocabulary: 'router' },
      { id: '175', vocabulary: 'modem' },
      { id: '176', vocabulary: 'firewall' },
      { id: '177', vocabulary: 'security' },
      { id: '178', vocabulary: 'encryption' },
      { id: '179', vocabulary: 'data' },
      { id: '180', vocabulary: 'analytics' },
      { id: '181', vocabulary: 'sensor' },
      { id: '182', vocabulary: 'robot' },
      { id: '183', vocabulary: 'automation' },
      { id: '184', vocabulary: 'blockchain' },
      { id: '185', vocabulary: 'bitcoin' },
      { id: '186', vocabulary: 'crypto' },
      { id: '187', vocabulary: 'USB' },
      { id: '188', vocabulary: 'Bluetooth' },
      { id: '189', vocabulary: 'Wi-Fi' },
      { id: '190', vocabulary: 'API' },
      { id: '191', vocabulary: 'SDK' },
      { id: '192', vocabulary: 'IDE' },
      { id: '193', vocabulary: 'compiler' },
      { id: '194', vocabulary: 'debugger' },
      { id: '195', vocabulary: 'framework' },
      { id: '196', vocabulary: 'library' },
      { id: '197', vocabulary: 'platform' },
      { id: '198', vocabulary: 'backend' },
      { id: '199', vocabulary: 'frontend' },
      { id: '200', vocabulary: 'fullstack' },
    ],
  },
];
