import type { VocabData } from './types';

export const WordChainMock: VocabData[] = [
  { id: '1', vocabs: ['cat', 'art', 'tar', 'cart'] },
  { id: '2', vocabs: ['dog', 'do', 'go'] },
  { id: '3', vocabs: ['bale', 'ale', 'lab'] },
  { id: '4', vocabs: ['sun', 'nun', 'us'] },
  { id: '5', vocabs: ['map', 'amp'] },
  { id: '6', vocabs: ['pen', 'net', 'ten'] },
  { id: '7', vocabs: ['row', 'own', 'now'] },
  { id: '8', vocabs: ['pig', 'rip', 'grip'] },
  { id: '9', vocabs: ['book', 'boo'] },
  { id: '10', vocabs: ['fire', 'fir', 'ire'] },
  { id: '11', vocabs: ['ball', 'all'] },
  { id: '12', vocabs: ['gas', 'sag', 'as'] },
  { id: '13', vocabs: ['leaf', 'ale', 'elf'] },
  { id: '14', vocabs: ['hill', 'ill'] },
  { id: '15', vocabs: ['fish', 'his', 'if'] },
  { id: '16', vocabs: ['milk', 'ilk'] },
  { id: '17', vocabs: ['rice', 'ice'] },
  { id: '18', vocabs: ['corn', 'ron'] },
  { id: '19', vocabs: ['flea', 'leaf'] },
  { id: '20', vocabs: ['rock', 'ock'] },
  { id: '21', vocabs: ['star', 'arts', 'rats'] },
  { id: '22', vocabs: ['ship', 'hip', 'sip'] },
  { id: '23', vocabs: ['time', 'mite'] },
  { id: '24', vocabs: ['wind', 'win'] },
  { id: '25', vocabs: ['tree', 'reel'] },
  { id: '26', vocabs: ['shoe', 'hoe'] },
  { id: '27', vocabs: ['hand', 'and'] },
  { id: '28', vocabs: ['head', 'had'] },
  { id: '29', vocabs: ['boat', 'tab', 'oat'] },
  { id: '30', vocabs: ['cold', 'old'] },
  { id: '31', vocabs: ['drop', 'rod'] },
  { id: '32', vocabs: ['lift', 'fit'] },
  { id: '33', vocabs: ['bell', 'ell'] },
  { id: '34', vocabs: ['farm', 'arm'] },
  { id: '35', vocabs: ['barn', 'ran'] },
  { id: '36', vocabs: ['camp', 'amp', 'map'] },
  { id: '37', vocabs: ['belt', 'let'] },
  { id: '38', vocabs: ['club', 'cub'] },
  { id: '39', vocabs: ['gold', 'dog'] },
  { id: '40', vocabs: ['band', 'and', 'nab'] },
  { id: '41', vocabs: ['park', 'ark', 'rap'] },
  { id: '42', vocabs: ['lamp', 'amp', 'palm'] },
  { id: '43', vocabs: ['rain', 'air', 'ran'] },
  { id: '44', vocabs: ['snow', 'now', 'sow'] },
  { id: '45', vocabs: ['heat', 'eat', 'tea'] },
  { id: '46', vocabs: ['warm', 'arm', 'ram'] },
  { id: '47', vocabs: ['blue', 'lube'] },
  { id: '48', vocabs: ['bake', 'beak'] },
  { id: '49', vocabs: ['rope', 'pore', 'repo'] },
  { id: '50', vocabs: ['salt', 'last', 'slat'] },
  { id: '51', vocabs: ['lime', 'mile', 'elm'] },
  { id: '52', vocabs: ['coal', 'cola'] },
  { id: '53', vocabs: ['note', 'tone', 'one'] },
  { id: '54', vocabs: ['sail', 'ails', 'ali'] },
  { id: '55', vocabs: ['sand', 'ands', 'sad'] },
  { id: '56', vocabs: ['park', 'rap'] },
  { id: '57', vocabs: ['coat', 'taco'] },
  { id: '58', vocabs: ['line', 'nil', 'lie'] },
  { id: '59', vocabs: ['morn', 'norm'] },
  { id: '60', vocabs: ['corn', 'cron'] },
  { id: '61', vocabs: ['tall', 'all'] },
  { id: '62', vocabs: ['pick', 'pic'] },
  { id: '63', vocabs: ['rock', 'cork'] },
  { id: '64', vocabs: ['pair', 'rap', 'air'] },
  { id: '65', vocabs: ['goal', 'ago'] },
  { id: '66', vocabs: ['spin', 'pins', 'nip'] },
  { id: '67', vocabs: ['song', 'snog'] },
  { id: '68', vocabs: ['send', 'ends', 'den'] },
  { id: '69', vocabs: ['park', 'dark', 'ark'] },
  { id: '70', vocabs: ['milk', 'skim'] },
  { id: '71', vocabs: ['bell', 'ble', 'leb'] },
  { id: '72', vocabs: ['fine', 'fen'] },
  { id: '73', vocabs: ['dear', 'read'] },
  { id: '74', vocabs: ['yard', 'dray'] },
  { id: '75', vocabs: ['vine', 'ive'] },
  { id: '76', vocabs: ['camp', 'scam'] },
  { id: '77', vocabs: ['bowl', 'low'] },
  { id: '78', vocabs: ['cash', 'has'] },
  { id: '79', vocabs: ['vine', 'nev'] },
  { id: '80', vocabs: ['mark', 'ark'] },
  { id: '81', vocabs: ['rope', 'peer'] },
  { id: '82', vocabs: ['foil', 'oil'] },
  { id: '83', vocabs: ['past', 'spa'] },
  { id: '84', vocabs: ['gard', 'drag'] },
  { id: '85', vocabs: ['peel', 'leep'] },
  { id: '86', vocabs: ['tape', 'peal'] },
  { id: '87', vocabs: ['bank', 'kanb'] },
  { id: '88', vocabs: ['gale', 'lag'] },
  { id: '89', vocabs: ['tile', 'lite'] },
  { id: '90', vocabs: ['pace', 'cape'] },
  { id: '91', vocabs: ['mend', 'den'] },
  { id: '92', vocabs: ['palm', 'lamp'] },
  { id: '93', vocabs: ['tone', 'note'] },
  { id: '94', vocabs: ['vase', 'save'] },
  { id: '95', vocabs: ['yarn', 'ran'] },
  { id: '96', vocabs: ['bolt', 'lot'] },
  { id: '97', vocabs: ['arch', 'car'] },
  { id: '98', vocabs: ['clap', 'lap'] },
  { id: '99', vocabs: ['dune', 'end'] },
  { id: '100', vocabs: ['eat', 'tea', 'ate'] },
];
