import { type VocabTopic } from '../FindWords/types';

export const vocabTopicsData: VocabTopic[] = [
  // Topic 1: Animals
  {
    id: '1',
    text: 'Animals',
    options: [
      { id: '1', vocabulary: 'dog' },
      { id: '2', vocabulary: 'cat' },
      { id: '3', vocabulary: 'bird' },
      { id: '4', vocabulary: 'fish' },
      { id: '5', vocabulary: 'cow' },
      { id: '6', vocabulary: 'pig' },
      { id: '7', vocabulary: 'lion' },
      { id: '8', vocabulary: 'wolf' },
      { id: '9', vocabulary: 'bear' },
      { id: '10', vocabulary: 'deer' },
      { id: '11', vocabulary: 'goat' },
      { id: '12', vocabulary: 'frog' },
      { id: '13', vocabulary: 'toad' },
      { id: '14', vocabulary: 'duck' },
      { id: '15', vocabulary: 'swan' },
      { id: '16', vocabulary: 'hare' },
      { id: '17', vocabulary: 'mole' },
      { id: '18', vocabulary: 'vole' },
      { id: '19', vocabulary: 'pony' },
      { id: '20', vocabulary: 'calf' },
      { id: '21', vocabulary: 'seal' },
      { id: '22', vocabulary: 'orca' },
      { id: '23', vocabulary: 'shark' },
      { id: '24', vocabulary: 'crab' },
      { id: '25', vocabulary: 'mule' },
    ],
  },

  // Topic 2: Food
  {
    id: '2',
    text: 'Food',
    options: [
      { id: '26', vocabulary: 'pear' },
      { id: '27', vocabulary: 'plum' },
      { id: '28', vocabulary: 'kiwi' },
      { id: '29', vocabulary: 'fig' },
      { id: '30', vocabulary: 'date' },
      { id: '31', vocabulary: 'bean' },
      { id: '32', vocabulary: 'corn' },
      { id: '33', vocabulary: 'rice' },
      { id: '34', vocabulary: 'cake' },
      { id: '35', vocabulary: 'milk' },
      { id: '36', vocabulary: 'egg' },
      { id: '37', vocabulary: 'ham' },
      { id: '38', vocabulary: 'beef' },
      { id: '39', vocabulary: 'pork' },
      { id: '40', vocabulary: 'tuna' },
      { id: '41', vocabulary: 'cod' },
      { id: '42', vocabulary: 'okra' },
      { id: '43', vocabulary: 'kale' },
      { id: '44', vocabulary: 'yams' },
      { id: '45', vocabulary: 'ziti' },
      { id: '46', vocabulary: 'soup' },
      { id: '47', vocabulary: 'wrap' },
      { id: '48', vocabulary: 'tart' },
      { id: '49', vocabulary: 'roll' },
      { id: '50', vocabulary: 'chip' },
    ],
  },

  // Topic 3: Travel
  {
    id: '3',
    text: 'Travel',
    options: [
      { id: '51', vocabulary: 'car' },
      { id: '52', vocabulary: 'bus' },
      { id: '53', vocabulary: 'taxi' },
      { id: '54', vocabulary: 'boat' },
      { id: '55', vocabulary: 'port' },
      { id: '56', vocabulary: 'road' },
      { id: '57', vocabulary: 'trip' },
      { id: '58', vocabulary: 'tour' },
      { id: '59', vocabulary: 'camp' },
      { id: '60', vocabulary: 'tent' },
      { id: '61', vocabulary: 'map' },
      { id: '62', vocabulary: 'gate' },
      { id: '63', vocabulary: 'pass' },
      { id: '64', vocabulary: 'visa' },
      { id: '65', vocabulary: 'limo' },
      { id: '66', vocabulary: 'bike' },
      { id: '67', vocabulary: 'ride' },
      { id: '68', vocabulary: 'rail' },
      { id: '69', vocabulary: 'stop' },
      { id: '70', vocabulary: 'seat' },
      { id: '71', vocabulary: 'inn' },
      { id: '72', vocabulary: 'info' },
      { id: '73', vocabulary: 'dock' },
      { id: '74', vocabulary: 'fare' },
      { id: '75', vocabulary: 'view' },
    ],
  },

  // Topic 4: Technology
  {
    id: '4',
    text: 'Technology',
    options: [
      { id: '76', vocabulary: 'code' },
      { id: '77', vocabulary: 'app' },
      { id: '78', vocabulary: 'web' },
      { id: '79', vocabulary: 'api' },
      { id: '80', vocabulary: 'sdk' },
      { id: '81', vocabulary: 'cpu' },
      { id: '82', vocabulary: 'gpu' },
      { id: '83', vocabulary: 'ram' },
      { id: '84', vocabulary: 'disk' },
      { id: '85', vocabulary: 'file' },
      { id: '86', vocabulary: 'node' },
      { id: '87', vocabulary: 'npm' },
      { id: '88', vocabulary: 'bash' },
      { id: '89', vocabulary: 'java' },
      { id: '90', vocabulary: 'rust' },
      { id: '91', vocabulary: 'html' },
      { id: '92', vocabulary: 'css' },
      { id: '93', vocabulary: 'sql' },
      { id: '94', vocabulary: 'data' },
      { id: '95', vocabulary: 'tech' },
      { id: '96', vocabulary: 'byte' },
      { id: '97', vocabulary: 'boot' },
      { id: '98', vocabulary: 'chip' },
      { id: '99', vocabulary: 'page' },
      { id: '100', vocabulary: 'auth' },
    ],
  },

  // Topic 5: Colors
  {
    id: '5',
    text: 'Colors',
    options: [
      { id: '101', vocabulary: 'red' },
      { id: '102', vocabulary: 'blue' },
      { id: '103', vocabulary: 'cyan' },
      { id: '104', vocabulary: 'teal' },
      { id: '105', vocabulary: 'aqua' },
      { id: '106', vocabulary: 'pink' },
      { id: '107', vocabulary: 'gold' },
      { id: '108', vocabulary: 'lime' },
      { id: '109', vocabulary: 'navy' },
      { id: '110', vocabulary: 'tan' },
      { id: '111', vocabulary: 'gray' },
      { id: '112', vocabulary: 'rose' },
      { id: '113', vocabulary: 'sand' },
      { id: '114', vocabulary: 'sage' },
      { id: '115', vocabulary: 'ruby' },
      { id: '116', vocabulary: 'mint' },
      { id: '117', vocabulary: 'iris' },
      { id: '118', vocabulary: 'plum' },
      { id: '119', vocabulary: 'coal' },
      { id: '120', vocabulary: 'jade' },
      { id: '121', vocabulary: 'ecru' },
      { id: '122', vocabulary: 'opal' },
      { id: '123', vocabulary: 'ebon' },
      { id: '124', vocabulary: 'peru' },
      { id: '125', vocabulary: 'mica' },
    ],
  },

  // Topic 6: Weather
  {
    id: '6',
    text: 'Weather',
    options: [
      { id: '126', vocabulary: 'sun' },
      { id: '127', vocabulary: 'rain' },
      { id: '128', vocabulary: 'snow' },
      { id: '129', vocabulary: 'hail' },
      { id: '130', vocabulary: 'wind' },
      { id: '131', vocabulary: 'mist' },
      { id: '132', vocabulary: 'fog' },
      { id: '133', vocabulary: 'gale' },
      { id: '134', vocabulary: 'warm' },
      { id: '135', vocabulary: 'cold' },
      { id: '136', vocabulary: 'temp' },
      { id: '137', vocabulary: 'hot' },
      { id: '138', vocabulary: 'icy' },
      { id: '139', vocabulary: 'dry' },
      { id: '140', vocabulary: 'wet' },
      { id: '141', vocabulary: 'gust' },
      { id: '142', vocabulary: 'bolt' },
      { id: '143', vocabulary: 'dusk' },
      { id: '144', vocabulary: 'dawn' },
      { id: '145', vocabulary: 'rays' },
      { id: '146', vocabulary: 'calm' },
      { id: '147', vocabulary: 'heat' },
      { id: '148', vocabulary: 'cool' },
      { id: '149', vocabulary: 'rime' },
      { id: '150', vocabulary: 'blow' },
    ],
  },

  // Topic 7: Sports
  {
    id: '7',
    text: 'Sports',
    options: [
      { id: '151', vocabulary: 'ball' },
      { id: '152', vocabulary: 'golf' },
      { id: '153', vocabulary: 'swim' },
      { id: '154', vocabulary: 'run' },
      { id: '155', vocabulary: 'judo' },
      { id: '156', vocabulary: 'surf' },
      { id: '157', vocabulary: 'ski' },
      { id: '158', vocabulary: 'curl' },
      { id: '159', vocabulary: 'team' },
      { id: '160', vocabulary: 'goal' },
      { id: '161', vocabulary: 'kick' },
      { id: '162', vocabulary: 'shot' },
      { id: '163', vocabulary: 'toss' },
      { id: '164', vocabulary: 'race' },
      { id: '165', vocabulary: 'row' },
      { id: '166', vocabulary: 'box' },
      { id: '167', vocabulary: 'foul' },
      { id: '168', vocabulary: 'club' },
      { id: '169', vocabulary: 'yoga' },
      { id: '170', vocabulary: 'lift' },
      { id: '171', vocabulary: 'arch' },
      { id: '172', vocabulary: 'punt' },
      { id: '173', vocabulary: 'slam' },
      { id: '174', vocabulary: 'ring' },
      { id: '175', vocabulary: 'drib' },
    ],
  },

  // Topic 8: Home
  {
    id: '8',
    text: 'Home',
    options: [
      { id: '176', vocabulary: 'bed' },
      { id: '177', vocabulary: 'sofa' },
      { id: '178', vocabulary: 'desk' },
      { id: '179', vocabulary: 'lamp' },
      { id: '180', vocabulary: 'door' },
      { id: '181', vocabulary: 'wall' },
      { id: '182', vocabulary: 'roof' },
      { id: '183', vocabulary: 'tile' },
      { id: '184', vocabulary: 'oven' },
      { id: '185', vocabulary: 'sink' },
      { id: '186', vocabulary: 'wash' },
      { id: '187', vocabulary: 'bath' },
      { id: '188', vocabulary: 'toil' },
      { id: '189', vocabulary: 'yard' },
      { id: '190', vocabulary: 'shed' },
      { id: '191', vocabulary: 'room' },
      { id: '192', vocabulary: 'home' },
      { id: '193', vocabulary: 'crib' },
      { id: '194', vocabulary: 'rug' },
      { id: '195', vocabulary: 'mat' },
      { id: '196', vocabulary: 'iron' },
      { id: '197', vocabulary: 'seat' },
      { id: '198', vocabulary: 'bench' },
      { id: '199', vocabulary: 'stnd' },
      { id: '200', vocabulary: 'cbin' },
    ],
  },

  // Topic 9: Nature
  {
    id: '9',
    text: 'Nature',
    options: [
      { id: '201', vocabulary: 'tree' },
      { id: '202', vocabulary: 'leaf' },
      { id: '203', vocabulary: 'rock' },
      { id: '204', vocabulary: 'sand' },
      { id: '205', vocabulary: 'soil' },
      { id: '206', vocabulary: 'pond' },
      { id: '207', vocabulary: 'reef' },
      { id: '208', vocabulary: 'wild' },
      { id: '209', vocabulary: 'fern' },
      { id: '210', vocabulary: 'moss' },
      { id: '211', vocabulary: 'cave' },
      { id: '212', vocabulary: 'peak' },
      { id: '213', vocabulary: 'lava' },
      { id: '214', vocabulary: 'hill' },
      { id: '215', vocabulary: 'dale' },
      { id: '216', vocabulary: 'bog' },
      { id: '217', vocabulary: 'dune' },
      { id: '218', vocabulary: 'seed' },
      { id: '219', vocabulary: 'root' },
      { id: '220', vocabulary: 'bloom' },
      { id: '221', vocabulary: 'vale' },
      { id: '222', vocabulary: 'pond' }, // small reuse is fine in mock
      { id: '223', vocabulary: 'spry' },
      { id: '224', vocabulary: 'reed' },
      { id: '225', vocabulary: 'sgeo' },
    ],
  },

  // Topic 10: School
  {
    id: '10',
    text: 'School',
    options: [
      { id: '226', vocabulary: 'book' },
      { id: '227', vocabulary: 'exam' },
      { id: '228', vocabulary: 'test' },
      { id: '229', vocabulary: 'math' },
      { id: '230', vocabulary: 'sci' },
      { id: '231', vocabulary: 'bio' },
      { id: '232', vocabulary: 'chem' },
      { id: '233', vocabulary: 'hist' },
      { id: '234', vocabulary: 'lang' },
      { id: '235', vocabulary: 'prof' },
      { id: '236', vocabulary: 'stud' },
      { id: '237', vocabulary: 'note' },
      { id: '238', vocabulary: 'bell' },
      { id: '239', vocabulary: 'mark' },
      { id: '240', vocabulary: 'lab' },
      { id: '241', vocabulary: 'memo' },
      { id: '242', vocabulary: 'grad' },
      { id: '243', vocabulary: 'club' },
      { id: '244', vocabulary: 'team' },
      { id: '245', vocabulary: 'proj' },
      { id: '246', vocabulary: 'room' },
      { id: '247', vocabulary: 'tute' },
      { id: '248', vocabulary: 'read' },
      { id: '249', vocabulary: 'page' },
      { id: '250', vocabulary: 'ctrl' },
    ],
  },
];
