import { moderateScale } from '@/shared/lib/helpers/scale';

export const scalingPoints = {
  '--fs-xxs': `${moderateScale(10)}px`,
  '--lh-xxs': `${moderateScale(14)}px`,
  '--fs-xs': `${moderateScale(12)}px`,
  '--lh-xs': `${moderateScale(16)}px`,
  '--fs-sm': `${moderateScale(14)}px`,
  '--lh-sm': `${moderateScale(20)}px`,
  '--fs-base': `${moderateScale(16)}px`,
  '--lh-base': `${moderateScale(24)}px`,
  '--fs-lg': `${moderateScale(18)}px`,
  '--lh-lg': `${moderateScale(26)}px`,
  '--fs-xl': `${moderateScale(20)}px`,
  '--lh-xl': `${moderateScale(28)}px`,
  '--fs-2xl': `${moderateScale(24)}px`,
  '--lh-2xl': `${moderateScale(32)}px`,
  '--fs-3xl': `${moderateScale(30)}px`,
  '--lh-3xl': `${moderateScale(36)}px`,

  '--space-0\.5': `${moderateScale(2)}px`,
  '--space-1': `${moderateScale(4)}px`,
  '--space-2': `${moderateScale(8)}px`,
  '--space-3': `${moderateScale(12)}px`,
  '--space-4': `${moderateScale(16)}px`,
  '--space-5': `${moderateScale(20)}px`,
  '--space-6': `${moderateScale(24)}px`,
  '--space-7': `${moderateScale(28)}px`,
  '--space-8': `${moderateScale(32)}px`,
  '--space-9': `${moderateScale(36)}px`,
  '--space-10': `${moderateScale(40)}px`,
  '--space-11': `${moderateScale(44)}px`,
  '--space-12': `${moderateScale(48)}px`,

  '--bw-0': `${moderateScale(0)}px`,
  '--bw-default': `${moderateScale(1)}px`,
  '--bw-2': `${moderateScale(2)}px`,
  '--bw-3': `${moderateScale(3)}px`,
  '--bw-4': `${moderateScale(4)}px`,
  '--bw-5': `${moderateScale(5)}px`,
  '--bw-6': `${moderateScale(6)}px`,
  '--bw-7': `${moderateScale(7)}px`,
  '--bw-8': `${moderateScale(8)}px`,
  '--bw-9': `${moderateScale(9)}px`,
  '--bw-10': `${moderateScale(10)}px`,
};
